import { createDhlClient } from "./client.ts";
import { normalizeDhlError } from "./errors.ts";
import { createDhlRepository } from "./repository.ts";
import type { DhlShipmentInput, DhlShipmentRecord } from "./types.ts";
import { validateDhlShipment } from "./validators.ts";
type Server = { middlewares: { use: (path: string, handler: (request: any, response: any) => void) => void } };
type Auth = { getSessionUser: (cookie?: string) => { permissions: string[] } | undefined };
export function registerDhlRoutes(server: Server, auth: Auth, env: Record<string, string>) { const client = createDhlClient(env); const repository = createDhlRepository(env); server.middlewares.use("/api/dhl", async (request, response) => { const user = auth.getSessionUser(request.headers.cookie); if (!user) return send(response, 401, { message: "Login requerido" }); if (!user.permissions.includes("expeditions")) return send(response, 403, { message: "Sin permiso de expediciones" }); const path = new URL(request.url || "/", "http://local").pathname.replace(/^\/+|\/+$/g, ""); try {
  if (request.method === "GET" && path === "status") return send(response, 200, client.status());
  if (request.method === "GET" && path === "shipments") return send(response, 200, { shipments: repository.list() });
  if (request.method === "POST" && path === "quotes") return send(response, 200, { quote: await client.quote(await body(request)) });
  if (request.method === "POST" && path === "shipments/real") { const input = await body<DhlShipmentInput>(request); validateDhlShipment(input); const existing = repository.find(input.reference); if (existing?.status === "created") return send(response, 409, { message: `Ya existe una expedición DHL válida para ${input.reference}`, shipment: existing }); if (existing?.status === "pending") return send(response, 409, { message: `La expedición DHL ${input.reference} sigue pendiente; no se creará un duplicado.`, shipment: existing }); if (existing?.status === "unknown") return send(response, 409, { message: `La expedición DHL ${input.reference} tiene resultado incierto. Revisión manual obligatoria.`, shipment: existing }); const now = new Date().toISOString(); repository.save({ reference: input.reference, status: "pending", carrierProduct: "B2C", createdAt: now, updatedAt: now }); try { const created = await client.createShipment(input) as Record<string, unknown>; const record: DhlShipmentRecord = { reference: input.reference, status: "created", year: String(created.Year || ""), tracking: String(created.Tracking || ""), awb: String(created.AWB || ""), licensePlates: Array.isArray(created.LP) ? created.LP.map(String) : [], labelBase64: String(created.Label || "").replace(/^data:application\/pdf;base64,/, ""), labelFormat: input.format || "PDF", carrierProduct: "B2C", createdAt: now, updatedAt: new Date().toISOString(), raw: sanitize(created) }; repository.save(record); return send(response, 201, { shipment: record }); } catch (error) { const detail = normalizeDhlError(error); const previous = repository.find(input.reference)!; repository.save({ ...previous, status: /timeout|abort|network/i.test(detail.original) ? "unknown" : "cancelled", updatedAt: new Date().toISOString(), providerErrorCode: detail.code, providerErrorMessage: detail.message }); return send(response, 502, { message: detail.message, error: detail }); } }
  const label = path.match(/^shipments\/([^/]+)\/label$/); if (request.method === "GET" && label) { const record = repository.findByReferenceOrTracking(decodeURIComponent(label[1])); if (!record?.labelBase64) return send(response, 404, { message: "Etiqueta DHL no disponible" }); response.statusCode = 200; response.setHeader("Content-Type", "application/pdf"); return response.end(Buffer.from(record.labelBase64, "base64")); }
  const print = path.match(/^shipments\/([^/]+)\/print$/); if (request.method === "POST" && print) { const record = repository.findByReferenceOrTracking(decodeURIComponent(print[1])); if (!record || record.status !== "created") return send(response, 404, { message: "Expedición DHL no reimprimible" }); return send(response, 200, { shipment: record }); }
  const remove = path.match(/^shipments\/([^/]+)$/); if (request.method === "DELETE" && remove) { const record = repository.findByReferenceOrTracking(decodeURIComponent(remove[1])); if (!record || record.status !== "created") return send(response, 404, { message: "Expedición DHL no encontrada" }); await client.remove(record.year || "", record.tracking || record.awb || record.reference); const next = { ...record, status: "cancelled" as const, cancelledAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; repository.save(next); return send(response, 200, { shipment: next }); }
  const track = path.match(/^shipments\/([^/]+)\/tracking$/); if (request.method === "GET" && track) return send(response, 200, { tracking: await client.track({ Tracking: decodeURIComponent(track[1]) }) });
  return send(response, 404, { message: "Ruta DHL no encontrada" });
} catch (error) { const detail = normalizeDhlError(error); const isInputError = /^DHL no puede generar la etiqueta:/.test(detail.message); return send(response, isInputError ? 400 : 502, { message: detail.message, error: detail }); } }); }
function sanitize(value: unknown) { const copy = JSON.parse(JSON.stringify(value || {})); if (copy && typeof copy === "object") { delete copy.Label; delete copy.Token; delete copy.token; } return copy; }
async function body<T = Record<string, unknown>>(request: { on: Function }) { const chunks: Buffer[] = []; await new Promise<void>((resolve, reject) => { request.on("data", (chunk: Buffer) => chunks.push(chunk)); request.on("end", resolve); request.on("error", reject); }); return (Buffer.concat(chunks).toString("utf8") ? JSON.parse(Buffer.concat(chunks).toString("utf8")) : {}) as T; }
function send(response: any, status: number, value: unknown) { response.statusCode = status; response.setHeader("Content-Type", "application/json; charset=utf-8"); response.end(JSON.stringify(value)); }
