import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, Clock3, LockKeyhole, MapPin, PackageCheck, Play, Plus, RefreshCw, Search, Trash2, UserRound, Warehouse, X } from "lucide-react";
import { odooClient } from "../../services/odooClient";
import type { CatalogProduct, InventoryReception, InventoryReceptionLine, InventoryReceptionsPayload, ReceptionLocationPlan, ReceptionSession } from "../../services/odooTypes";
import { allocatedQuantity, createLocationPlan, isLocationPlanBalanced, normalizedQuantity } from "./locationPlan";
import "./inventory-receptions.css";

const planKey = "dashboard.reception-location-plans.v1";
type Worker = { id: string; code: string; name: string };

export function InventoryReceptionsView() {
  const [data, setData] = useState<InventoryReceptionsPayload | null>(null);
  const [sessions, setSessions] = useState<ReceptionSession[]>([]);
  const [plans, setPlans] = useState<Record<string, ReceptionLocationPlan>>(() => { try { return JSON.parse(localStorage.getItem(planKey) || "{}"); } catch { return {}; } });
  const [selected, setSelected] = useState<InventoryReception | null>(null);
  const [openPlan, setOpenPlan] = useState<string | null>(null);
  const [extras, setExtras] = useState<Record<string, InventoryReceptionLine[]>>({});
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Todas");
  const [code, setCode] = useState(""); const [starting, setStarting] = useState(false); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { setBusy(true); setError(""); try { const result = await Promise.all([odooClient.getInventoryReceptions(), odooClient.getReceptionSessions().catch(() => [])]); setData(result[0]); setSessions(result[1]); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron leer las recepciones."); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []); useEffect(() => { localStorage.setItem(planKey, JSON.stringify(plans)); }, [plans]);
  const active = useMemo(() => new Map(sessions.filter((item) => item.status === "in_progress").map((item) => [item.receptionId, item])), [sessions]);
  const receptions = useMemo(() => { const value = query.trim().toLocaleLowerCase("es"); return (data?.receptions ?? []).filter((item) => (filter === "Todas" || item.status === filter) && (!value || [item.purchaseRef, item.supplier, item.supplierRef || "", item.ref, ...item.lines.flatMap((line) => [line.name, line.sku, line.barcode, ...line.saleOrderRefs])].some((text) => text.toLocaleLowerCase("es").includes(value)))); }, [data, filter, query]);
  const start = async () => { if (!selected || !code.trim()) return; setBusy(true); try { const path = "/api/warehouse-workers/resolve/" + encodeURIComponent(code.trim().toUpperCase()); const response = await fetch(window.location.pathname.startsWith("/inventory-lab/") ? "/inventory-lab" + path : path); const result = await response.json() as { worker?: Worker; message?: string }; if (!response.ok || !result.worker) throw new Error(result.message || "QR de operario no válido o inactivo."); const session = await odooClient.startReceptionSession({ receptionId: selected.id, receptionRef: selected.ref, purchaseRef: selected.purchaseRef, operator: result.worker }); setSessions((items) => [session, ...items.filter((item) => item.receptionId !== selected.id)]); setStarting(false); setCode(""); setMessage("Recepción iniciada por " + session.operator.name); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo iniciar la recepción."); } finally { setBusy(false); } };
  const end = async (release: boolean) => { if (!selected) return; setBusy(true); try { const session = release ? await odooClient.cancelReceptionSession(selected.id) : await odooClient.completeReceptionSession(selected.id); setSessions((items) => release ? items.filter((item) => item.receptionId !== selected.id) : items.map((item) => item.receptionId === selected.id ? session : item)); setMessage(release ? "Recepción liberada. No se ha modificado Odoo." : "Sesión finalizada."); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo actualizar la sesión."); } finally { setBusy(false); } };
  const addExtra = (product: CatalogProduct) => { if (!selected) return; const line: InventoryReceptionLine = { id: "extra-" + selected.id + "-" + product.id + "-" + Date.now(), productId: String(product.id), name: product.name, sku: product.reference, barcode: product.barcode, expectedQty: 1, processedQty: 0, pendingQty: 1, uom: product.uom || "uds", classification: "replenishment", saleOrderRefs: [], preferredLocation: product.locationSummary?.preferredCode }; setExtras((items) => ({ ...items, [selected.id]: [...(items[selected.id] || []), line] })); setMessage("Producto añadido a la sesión local. No se ha modificado el pedido de compra ni Odoo."); };
  return <section className="inventory-receptions">
    <header className="inventory-receptions-hero"><div><span>Inventario Odoo · Solo lectura</span><h2>Recepciones de almacén</h2><p>Clasificación real por pedido de venta y propuesta de ubicación.</p></div><button onClick={() => void load()} type="button"><RefreshCw className={busy ? "inventory-spin" : ""} size={17}/>Actualizar</button></header>
    <div className="inventory-receptions-kpis"><Kpi label="Recepciones abiertas" value={data?.total || 0}/><Kpi label="Preparadas" value={data?.ready || 0}/><Kpi label="Esperando" value={data?.waiting || 0}/><Kpi label="Líneas pendientes" value={data?.pendingLines || 0}/></div>
    <div className="inventory-receptions-toolbar"><label><Search size={18}/><input onChange={(e) => setQuery(e.target.value)} placeholder="Buscar PO, proveedor, SO, SKU o EAN" value={query}/></label><div>{["Todas", "Preparada", "Esperando"].map((item) => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)} type="button">{item}</button>)}</div></div>
    {error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}{!busy && !receptions.length && <div className="inventory-receptions-empty"><Warehouse size={36}/><strong>No hay recepciones con estos filtros</strong></div>}
    <div className="inventory-receptions-list">{receptions.map((item) => <article className="inventory-reception-card" key={item.id}><button className="inventory-reception-summary" onClick={() => setSelected(item)} type="button"><span className="inventory-reference"><small>Pedido de compra</small><strong>{item.purchaseRef || item.ref}</strong>{active.get(item.id) && <em>En curso · {active.get(item.id)?.operator.name}</em>}</span><span className="inventory-supplier"><strong>{item.supplier}</strong>{item.supplierRef && <small>Ref. proveedor: {item.supplierRef}</small>}</span><Metric expected={item.expectedQty} received={item.processedQty} pending={item.pendingQty}/><ChevronRight size={20}/></button></article>)}</div>
    {selected && <Detail reception={selected} session={active.get(selected.id)} lines={[...selected.lines, ...(extras[selected.id] || [])]} plans={plans} openPlan={openPlan} starting={starting} code={code} busy={busy} onClose={() => { setSelected(null); setOpenPlan(null); }} onStart={() => setStarting(true)} onCancel={() => setStarting(false)} onCode={setCode} onBegin={start} onEnd={end} onAdd={addExtra} onPlan={(line) => { setPlans((items) => items[line.id] ? items : { ...items, [line.id]: createLocationPlan(line) }); setOpenPlan((id) => id === line.id ? null : line.id); }} onChange={(id, plan) => setPlans((items) => ({ ...items, [id]: { ...plan, ready: false } }))}/>}
  </section>;
}

function Detail({ reception, session, lines, plans, openPlan, starting, code, busy, onClose, onStart, onCancel, onCode, onBegin, onEnd, onAdd, onPlan, onChange }: { reception: InventoryReception; session?: ReceptionSession; lines: InventoryReceptionLine[]; plans: Record<string, ReceptionLocationPlan>; openPlan: string | null; starting: boolean; code: string; busy: boolean; onClose: () => void; onStart: () => void; onCancel: () => void; onCode: (v: string) => void; onBegin: () => void; onEnd: (release: boolean) => void; onAdd: (p: CatalogProduct) => void; onPlan: (line: InventoryReceptionLine) => void; onChange: (id: string, plan: ReceptionLocationPlan) => void }) {
  const [picker, setPicker] = useState(false); const [catalog, setCatalog] = useState<CatalogProduct[]>([]); const [term, setTerm] = useState("");
  const results = catalog.filter((item) => !term || [item.name, item.reference, item.barcode].join(" ").toLocaleLowerCase("es").includes(term.toLocaleLowerCase("es"))).slice(0, 8);
  const loadCatalog = async () => { setPicker(true); if (!catalog.length) setCatalog((await odooClient.getProductCatalog()).products); };
  return <div className="inventory-reception-drawer-backdrop"><aside className="inventory-reception-drawer"><header><div><small>Recepción de pedido</small><h2>{reception.purchaseRef || reception.ref}</h2><p>{reception.supplier}</p></div><button onClick={onClose} type="button"><X size={20}/></button></header><div className="inventory-drawer-summary"><span>Entrada Odoo <strong>{reception.ref}</strong></span><span>Destino <strong>{reception.destination}</strong></span><Metric expected={reception.expectedQty} received={reception.processedQty} pending={reception.pendingQty}/></div>
    {!session ? <div className="inventory-session-gate"><div><LockKeyhole size={18}/><strong>Identifica al operario para empezar</strong><span>No se pueden repartir ubicaciones ni editar cantidades hasta iniciar la recepción.</span></div>{starting ? <><label>QR de un operario activo<input autoFocus onChange={(e) => onCode(e.target.value)} value={code}/></label><button disabled={!code || busy} onClick={onBegin} type="button"><Play size={16}/>Empezar recepción</button><button className="text" onClick={onCancel} type="button">Cancelar</button></> : <button className="inventory-start-button" onClick={onStart} type="button"><Play size={16}/>Iniciar recepción</button>}</div> : <div className="inventory-active-session"><UserRound size={17}/><span><strong>{session.operator.name}</strong><small>Operario activo</small></span><button className="inventory-release-session" onClick={() => onEnd(true)} type="button">Liberar</button><button onClick={() => onEnd(false)} type="button"><CheckCircle2 size={16}/>Finalizar sesión</button></div>}
    {session && <><div className="inventory-add-unexpected"><div><strong>¿Ha llegado un producto no esperado?</strong><span>Añádelo solo a esta sesión. No modifica el pedido de compra ni Odoo.</span></div><button onClick={() => void loadCatalog()} type="button"><Plus size={16}/>Añadir producto</button></div>{picker && <div className="inventory-unexpected-picker"><label>Buscar en el catálogo<input autoFocus onChange={(e) => setTerm(e.target.value)} placeholder="Nombre, referencia o EAN" value={term}/></label><div>{results.map((product) => <button key={product.id} onClick={() => { onAdd(product); setPicker(false); }} type="button"><strong>{product.name}</strong><span>{product.reference} · {product.barcode}</span></button>)}</div><button className="cancel" onClick={() => setPicker(false)} type="button">Cancelar</button></div>}</>}
    <div className="inventory-reception-lines">{lines.map((line) => <article className="inventory-reception-line" key={line.id}><div className="inventory-reception-line-main"><div className="inventory-product-image"><PackageCheck size={22}/></div><div className="inventory-product-copy"><strong>{line.name}</strong><span>{line.sku} · EAN {line.barcode}</span><Classification line={line}/></div><div className="inventory-line-metrics"><span>Esperada <b>{line.expectedQty}</b></span><span>Recibida <b>{line.processedQty}</b></span><span>Pendiente <b>{line.pendingQty}</b></span></div>{session ? <button className="inventory-plan-toggle" onClick={() => onPlan(line)} type="button"><MapPin size={16}/>{openPlan === line.id ? "Cerrar reparto" : "Repartir ubicación"}</button> : <span className="inventory-locked-action"><LockKeyhole size={15}/>Inicia recepción</span>}</div>{session && openPlan === line.id && plans[line.id] && <Plan line={line} plan={plans[line.id]} onChange={(plan) => onChange(line.id, plan)}/>}</article>)}</div>
  </aside></div>;
}

function Classification({ line }: { line: InventoryReceptionLine }) { if (line.classification === "under_order") { const ref = line.saleOrderRefs[0] || ""; return <div className="inventory-line-classification under-order"><b>🔴 BAJO PEDIDO · PENDIENTE DE ENVÍO</b><span>Reservado para <a href={"#/expediciones?pedido=" + encodeURIComponent(ref)}>{line.saleOrderRefs.join(", ")}</a>. No guardar en almacén.</span></div>; } return <div className="inventory-line-classification replenishment"><b>🟠 REPOSICIÓN</b><span>📍 Ubicación preferente: {line.preferredLocation || "Indicar al recibir"}</span></div>; }
function Plan({ line, plan, onChange }: { line: InventoryReceptionLine; plan: ReceptionLocationPlan; onChange: (plan: ReceptionLocationPlan) => void }) { const total = allocatedQuantity(plan.allocations); const balanced = isLocationPlanBalanced(plan); const partial = plan.receivedQty < line.pendingQty; return <div className="inventory-location-plan"><header><div><strong>Distribución física {partial ? "parcial" : "propuesta"}</strong><span>{partial ? "Quedará cantidad como parcial pendiente." : "Las ubicaciones reales pueden ser distintas de la preferente."}</span></div><label>Cantidad a recibir<input onChange={(e) => onChange({ ...plan, receivedQty: normalizedQuantity(e.target.value) })} type="number" value={plan.receivedQty}/></label></header><div className="inventory-allocation-list">{plan.allocations.map((item, index) => <div className="inventory-allocation-row" key={item.id}><span>{index + 1}</span><label>Ubicación real<input onChange={(e) => onChange({ ...plan, allocations: plan.allocations.map((x) => x.id === item.id ? { ...x, location: e.target.value } : x) })} value={item.location}/></label><label>Cantidad<input onChange={(e) => onChange({ ...plan, allocations: plan.allocations.map((x) => x.id === item.id ? { ...x, quantity: normalizedQuantity(e.target.value) } : x) })} type="number" value={item.quantity}/></label><button className="inventory-delete-allocation" onClick={() => onChange({ ...plan, allocations: plan.allocations.filter((x) => x.id !== item.id) })} type="button"><Trash2 size={17}/></button></div>)}</div><button className="inventory-add-allocation" onClick={() => onChange({ ...plan, allocations: [...plan.allocations, { id: line.id + "-" + Date.now(), location: "", quantity: 0 }] })} type="button"><Plus size={16}/>Añadir ubicación</button><footer className={balanced ? "balanced" : "unbalanced"}><div><strong>{total} de {plan.receivedQty} uds. repartidas</strong><span>{balanced ? "Propuesta local preparada." : "La suma debe coincidir."}</span></div><button disabled={!balanced} onClick={() => onChange({ ...plan, ready: true })} type="button">Guardar reparto</button></footer></div>; }
function Metric({ expected, received, pending }: { expected: number; received: number; pending: number }) { return <span className="inventory-receipt-metrics"><span><Clock3 size={16}/><b>{expected}</b></span><span><PackageCheck size={16}/><b>{received}</b></span><span><AlertTriangle size={16}/><b>{pending}</b></span></span>; }
function Kpi({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Notice({ children, error = false }: { children: string; error?: boolean }) { return <div className={"inventory-receptions-notice" + (error ? " error" : " success")}><AlertTriangle size={19}/>{children}</div>; }
