import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const vite = readFileSync(new URL("../vite.config.ts", import.meta.url), "utf8");
const client = readFileSync(new URL("../src/services/odooClient.ts", import.meta.url), "utf8");
const view = readFileSync(new URL("../src/modules/receptions/InventoryReceptionsView.tsx", import.meta.url), "utf8");

assert.match(vite, /url\.pathname === "\/validate"/);
assert.match(vite, /url\.pathname === "\/cancel"/);
assert.match(vite, /user\.permissions\.includes\("odooWrite"\)/);
assert.match(vite, /Las líneas han cambiado en Odoo/);
assert.match(vite, /stock\.backorder\.confirmation/);
assert.match(vite, /createBackorder \? "process" : "process_cancel_backorder"/);
assert.match(vite, /pendingReception:/);
assert.match(vite, /model === "stock\.move" && method === "create"/);
assert.match(vite, /model === "stock\.picking" && \["button_validate", "action_cancel"\]/);
assert.match(client, /validateInventoryReception/);
assert.match(client, /cancelInventoryReception/);
assert.match(view, /Validando…/);
assert.match(view, /Cancelando en Odoo…/);
assert.match(view, /disabled=\{validating/);
assert.match(vite, /fields: \["id", "partner_ref", "order_type"\]/);
assert.match(vite, /=== "rebastecimiento"/);
assert.match(view, /useState<ReceptionFilter>\("Esperando"\)/);
assert.match(view, /filter === "Importaciones" \? item\.isImportation/);
assert.match(view, /item\.status === filter && !item\.isImportation/);
assert.match(view, /Página \{historyPage\} de \{historyPages\}/);
assert.match(view, /onSubmit=\{\(event\) => \{ event\.preventDefault\(\); if \(!validating\) void validateReception\(\); \}\}/);
assert.match(view, /setDecision\(pendingAfterReceipt > 0 \? "backorder" : ""\)/);
assert.match(view, /const preparedUnits = readyLines\.reduce/);
assert.match(view, /Unidades preparadas/);
assert.match(view, /Unidades pendientes/);
assert.match(view, /Al aceptar, esta recepción se enviará directamente en Odoo|Al aceptar, esta recepción se enviará directamente a Odoo/);
assert.doesNotMatch(view, /Resumen antes de validar/);
assert.match(view, /<button autoFocus className="primary-button"/);
assert.match(view, /type="submit">\{validating \?/);
assert.match(view, /<RefreshCw className="inventory-spin" size=\{16\}\/>Validando…/);
assert.match(view, /type="button">Cancelar<\/button>/);
assert.match(view, /inventory-validation-modal-backdrop/);
assert.match(view, /event\.key === "Escape"/);
assert.match(view, /event\.key !== "Tab"/);
assert.match(view, /validationButtonRef\.current\?\.focus\(\)/);
assert.doesNotMatch(view, /validateSimulation|cancelSimulation|Confirmar simulación/);

console.log("Recepciones Fase 5: escritura Odoo, permisos y feedback verificados");
