import { useEffect, useMemo, useState } from "react";
import { downloadWorkerQr, workerQrDataUrl } from "../expeditions/workerQr";

type Activity = { id: string; workerId: string; workerName: string; workerCode: string; orderRef: string; carrier?: string; tracking?: string; result?: "label-created" | "simulated-label"; createdAt: string };
type Worker = { id: string; code: string; name: string; active: boolean };
type Range = "today" | "hours" | "week" | "month";
const apiPath = (path: string) => { const match = window.location.pathname.match(/^\/(expeditions-(?:lab|redesign-lab))/); return match ? `/${match[1]}${path}` : path; };
const labels: Record<Range, string> = { today: "Hoy", hours: "Por horas", week: "7 laborables", month: "Mes" };
const dateKey = (date: Date) => date.toISOString().slice(0, 10);
function startOfRange(range: Range) { const now = new Date(); if (range === "today" || range === "hours") return new Date(now.getFullYear(), now.getMonth(), now.getDate()); if (range === "week") { const day = now.getDay() || 7; const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); let remaining = 7; while (remaining > 1) { start.setDate(start.getDate() - 1); if (start.getDay() !== 0 && start.getDay() !== 6) remaining--; } return start; } return new Date(now.getFullYear(), now.getMonth(), 1); }
export function WarehouseStatisticsView() {
  const [activities, setActivities] = useState<Activity[]>([]); const [warehouseWorkers, setWarehouseWorkers] = useState<Worker[]>([]); const [range, setRange] = useState<Range>("today"); const [worker, setWorker] = useState("all"); const [qrDataUrl, setQrDataUrl] = useState("");
  const load = async () => { const response = await fetch(apiPath("/api/warehouse-workers/statistics")); if (response.ok) setActivities(((await response.json()) as { activities?: Activity[] }).activities || []); };
  const loadWorkers = async () => { const response = await fetch(apiPath("/api/warehouse-workers/statistics/workers")); if (response.ok) setWarehouseWorkers(((await response.json()) as { workers?: Worker[] }).workers || []); };
  useEffect(() => { void load(); void loadWorkers(); }, []);
  const selectedWorker = useMemo(() => warehouseWorkers.find((item) => item.id === worker) || null, [warehouseWorkers, worker]);
  useEffect(() => { setQrDataUrl(""); if (selectedWorker) void workerQrDataUrl(selectedWorker).then(setQrDataUrl); }, [selectedWorker]);
  const filtered = useMemo(() => { const start = startOfRange(range).getTime(); return activities.filter((item) => new Date(item.createdAt).getTime() >= start && (worker === "all" || item.workerId === worker)); }, [activities, range, worker]);
  const byWorker = useMemo(() => Object.entries(filtered.reduce<Record<string, number>>((out, item) => { out[item.workerName] = (out[item.workerName] || 0) + 1; return out; }, {})).sort((a, b) => b[1] - a[1]), [filtered]);
  const buckets = useMemo(() => { const map = new Map<string, number>(); if (range === "hours" || range === "today") for (let h = 0; h < 24; h++) map.set(`${String(h).padStart(2, "0")}:00`, 0); filtered.forEach((item) => { const date = new Date(item.createdAt); const key = range === "hours" || range === "today" ? `${String(date.getHours()).padStart(2, "0")}:00` : dateKey(date); map.set(key, (map.get(key) || 0) + 1); }); return [...map.entries()]; }, [filtered, range]);
  const max = Math.max(1, ...buckets.map(([, total]) => total)); const currentHour = new Date().getHours(); const currentHourCount = filtered.filter((item) => new Date(item.createdAt).getHours() === currentHour).length; const minute = new Date().getMinutes(); const currentRate = minute ? (currentHourCount / minute) * 60 : currentHourCount;
  return <section className="warehouse-stats">
    <header className="warehouse-stats-hero"><div><span>Estadísticas de almacén</span><h2>Producción por operario</h2><p>Etiquetas nuevas registradas por QR. Sin estimaciones ni datos de prueba.</p></div><div className="warehouse-stats-live"><i />Datos reales<br /><small>Actualiza al abrir</small></div></header>
    <div className="warehouse-stats-controls"><div>{(Object.keys(labels) as Range[]).map((key) => <button className={range === key ? "active" : ""} key={key} onClick={() => setRange(key)} type="button">{labels[key]}</button>)}</div><select aria-label="Filtrar por operario" onChange={(event) => setWorker(event.target.value)} value={worker}><option value="all">Todos los operarios</option>{warehouseWorkers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={() => { void load(); void loadWorkers(); }} type="button">Actualizar</button></div>
    {selectedWorker ? <article className="panel warehouse-worker-qr"><div><span>QR DEL OPERARIO</span><h3>{selectedWorker.name}</h3><p>{selectedWorker.code} · 40 × 40 mm · listo para imprimir</p><button onClick={() => void downloadWorkerQr(selectedWorker)} type="button">Descargar QR</button></div>{qrDataUrl ? <img alt={`Código QR de ${selectedWorker.name}`} src={qrDataUrl} /> : <div className="warehouse-qr-loading">Generando QR…</div>}</article> : null}
    <div className="warehouse-kpis"><article><span>Etiquetas nuevas</span><strong>{filtered.length}</strong><small>{labels[range]}</small></article><article><span>Operarios con actividad</span><strong>{byWorker.length}</strong><small>En el periodo elegido</small></article><article><span>Ritmo hora actual</span><strong>{currentRate.toFixed(1)}</strong><small>Etiquetas/h · acumulado real</small></article></div>
    <div className="warehouse-charts"><article className="panel warehouse-chart-panel"><div className="warehouse-panel-head"><div><h3>Etiquetas por franja</h3><small>Distribución del período</small></div><b>{filtered.length} total</b></div><div className="warehouse-bars">{buckets.map(([label, total]) => <div className="warehouse-bar" key={label} title={`${label}: ${total} etiquetas`}><i style={{ height: `${Math.max(total ? 8 : 0, (total / max) * 100)}%` }} /><span>{label}</span></div>)}</div></article><article className="panel warehouse-chart-panel"><div className="warehouse-panel-head"><div><h3>Por operario</h3><small>Comparativa directa</small></div></div>{byWorker.length ? <div className="warehouse-worker-list">{byWorker.map(([name, total]) => <div key={name}><span>{name}</span><b>{total}</b><i><em style={{ width: `${(total / Math.max(...byWorker.map(([, value]) => value))) * 100}%` }} /></i></div>)}</div> : <p className="warehouse-empty">Aún no hay etiquetas nuevas registradas en este periodo.</p>}</article></div>
    <article className="panel warehouse-detail"><div className="warehouse-panel-head"><div><h3>Detalle verificable</h3><small>Cada cifra procede de una etiqueta generada</small></div></div><div className="table-scroll"><table className="orders-table"><thead><tr><th>Fecha y hora</th><th>Operario</th><th>Pedido</th><th>Transportista</th><th>Tracking</th></tr></thead><tbody>{filtered.slice().sort((a,b) => b.createdAt.localeCompare(a.createdAt)).map((item) => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString("es-ES")}</td><td><strong>{item.workerName}</strong><small>{item.workerCode}</small></td><td>{item.orderRef}</td><td>{item.result === "simulated-label" ? `PRUEBA · ${item.carrier || "Sin dato"}` : item.carrier || "Sin dato"}</td><td>{item.tracking || "Sin dato"}</td></tr>)}{!filtered.length && <tr><td colSpan={5} className="empty-state">No hay etiquetas nuevas registradas para este filtro.</td></tr>}</tbody></table></div></article>
  </section>;
}
